Documentation cleanup
alpenlabs/strata-bridge-poc pull request #13
Opened 2024-12-03 19:57 UTC by AaronFeickert

## Description

Cleans up the front-facing documentation

### Type of Change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature/Enhancement (non-breaking change which adds functionality or enhances an existing one)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [x] Documentation update
-   [ ] Refactor

## Checklist

-   [x] I have performed a self-review of my code.
-   [x] I have commented my code where necessary.
-   [x] I have updated the documentation if needed.
-   [x] My changes do not introduce new warnings.
-   [ ] I have added tests that prove my changes are effective or that my feature works.
-   [x] New and existing tests pass with my changes.

## Related Issues

None.

2024-12-03 20:01 UTC, Rajil1213 requested changes
Minor typo, otherwise looks fine.

2024-12-03 20:01 UTC, Rajil1213 commented on README.md
> +    <figcaption>The transaction graph for this repository, focusing on the non-optimistic path.</figcaption>
```suggestion
    <figcaption>The transaction graph for this repository, focussing on the non-optimistic path.</figcaption>
```

2024-12-03 20:02 UTC, AaronFeickert commented on README.md
> +    <figcaption>The transaction graph for this repository, focusing on the non-optimistic path.</figcaption>
Ah, I wasn't aware this was a (presumably non-American English) spelling!

2024-12-03 20:04 UTC, Rajil1213 commented on README.md
> +    <figcaption>The transaction graph for this repository, focusing on the non-optimistic path.</figcaption>
I wasn't aware that's the American spelling. 😅

Fine to leave as is then.

2024-12-03 20:05 UTC, AaronFeickert commented on README.md
> +    <figcaption>The transaction graph for this repository, focusing on the non-optimistic path.</figcaption>
I have no preference. Apparently both spellings are generally considered valid. Already reverted.

2024-12-03 20:05 UTC, Rajil1213 submitted a review, later dismissed

2024-12-03 20:43 UTC, storopoli commented
I would add links to these resources:

```md
-   SP1 Toolchain and associated linkers.
-   Credentials to connect to SP1's infra.
-   Docker.
-   `sqlx-cli` to run migrations.
```

2024-12-04 09:56 UTC, Rajil1213 commented
Rebased this PR with `main` and also added links to the prerequisites as suggested by Jose.

2024-12-04 10:00 UTC, merged

2024-12-04 10:21 UTC, storopoli commented
> Rebased this PR with `main` (for a CI fix) and also added links to the prerequisites as suggested by Jose.

Thank you.